// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aceta_app_api.Data;

#nullable disable

namespace aceta_app_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250520200502_20.05.23.04")]
    partial class _20052304
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aceta_app_api.Models.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracMarkasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracYili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlakaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracMarka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracTurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracTurId");

                    b.ToTable("AracMarkalar");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracMarkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracMarkaId");

                    b.ToTable("AracModeller");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracTur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AracTurler");
                });

            modelBuilder.Entity("aceta_app_api.Models.CekiciBireysel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Boylam")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("CekebilecegiAraclar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DestekEkipmanlari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Enlem")
                        .HasColumnType("float");

                    b.Property<decimal>("KmBasiUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlakaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TasimaSistemleri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TeknikEkipmanlari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CekiciBireyseller");
                });

            modelBuilder.Entity("aceta_app_api.Models.CekiciFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Boylam")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("CekebilecegiAraclar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("DestekEkipmanlari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Enlem")
                        .HasColumnType("float");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KmBasiUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlakaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TasimaSistemleri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("TeknikEkipmanlari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CekiciFirmalar");
                });

            modelBuilder.Entity("aceta_app_api.Models.CekiciRandevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("CekiciBaslangıcKonumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CekiciBireyselId")
                        .HasColumnType("int");

                    b.Property<int?>("CekiciFirmaId")
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GeldimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciBaslangıcKonumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("CekiciBireyselId");

                    b.HasIndex("CekiciFirmaId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("CekiciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.DonanimDestekEkipman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OzellikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonanimDestekEkipmanlar");
                });

            modelBuilder.Entity("aceta_app_api.Models.DonanimTasimaSistem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OzellikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonanimTasimaSistemler");
                });

            modelBuilder.Entity("aceta_app_api.Models.DonanimTeknikEkipman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OzellikAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonanimTeknikEkipmanlar");
                });

            modelBuilder.Entity("aceta_app_api.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EPosta")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("aceta_app_api.Models.TamirciBireysel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracMarkasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DukkanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TamirciBireyseller");
                });

            modelBuilder.Entity("aceta_app_api.Models.TamirciFirma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracMarkasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModeli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DukkanAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TamirciFirmalar");
                });

            modelBuilder.Entity("aceta_app_api.Models.TamirciRandevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciBaslangıcKonumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("OncesiFotograflar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("SonrasiFotograflar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TamirciBaslangıcKonumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TamirciBireyselId")
                        .HasColumnType("int");

                    b.Property<int?>("TamirciFirmaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("TamirciBireyselId");

                    b.HasIndex("TamirciFirmaId");

                    b.ToTable("TamirciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracMarka", b =>
                {
                    b.HasOne("aceta_app_api.Models.AracTur", "AracTur")
                        .WithMany("Markalar")
                        .HasForeignKey("AracTurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AracTur");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracModel", b =>
                {
                    b.HasOne("aceta_app_api.Models.AracMarka", "AracMarka")
                        .WithMany("Modeller")
                        .HasForeignKey("AracMarkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AracMarka");
                });

            modelBuilder.Entity("aceta_app_api.Models.CekiciRandevu", b =>
                {
                    b.HasOne("aceta_app_api.Models.Arac", "Arac")
                        .WithMany("CekiciRandevular")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aceta_app_api.Models.CekiciBireysel", "CekiciBireysel")
                        .WithMany("CekiciRandevular")
                        .HasForeignKey("CekiciBireyselId");

                    b.HasOne("aceta_app_api.Models.CekiciFirma", "CekiciFirma")
                        .WithMany("CekiciRandevular")
                        .HasForeignKey("CekiciFirmaId");

                    b.HasOne("aceta_app_api.Models.Kullanici", "Kullanici")
                        .WithMany("CekiciRandevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("CekiciBireysel");

                    b.Navigation("CekiciFirma");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("aceta_app_api.Models.TamirciRandevu", b =>
                {
                    b.HasOne("aceta_app_api.Models.Arac", "Arac")
                        .WithMany("TamirciRandevular")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aceta_app_api.Models.Kullanici", "Kullanici")
                        .WithMany("TamirciRandevular")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aceta_app_api.Models.TamirciBireysel", "TamirciBireysel")
                        .WithMany("TamirciRandevular")
                        .HasForeignKey("TamirciBireyselId");

                    b.HasOne("aceta_app_api.Models.TamirciFirma", "TamirciFirma")
                        .WithMany("TamirciRandevular")
                        .HasForeignKey("TamirciFirmaId");

                    b.Navigation("Arac");

                    b.Navigation("Kullanici");

                    b.Navigation("TamirciBireysel");

                    b.Navigation("TamirciFirma");
                });

            modelBuilder.Entity("aceta_app_api.Models.Arac", b =>
                {
                    b.Navigation("CekiciRandevular");

                    b.Navigation("TamirciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracMarka", b =>
                {
                    b.Navigation("Modeller");
                });

            modelBuilder.Entity("aceta_app_api.Models.AracTur", b =>
                {
                    b.Navigation("Markalar");
                });

            modelBuilder.Entity("aceta_app_api.Models.CekiciBireysel", b =>
                {
                    b.Navigation("CekiciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.CekiciFirma", b =>
                {
                    b.Navigation("CekiciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.Kullanici", b =>
                {
                    b.Navigation("CekiciRandevular");

                    b.Navigation("TamirciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.TamirciBireysel", b =>
                {
                    b.Navigation("TamirciRandevular");
                });

            modelBuilder.Entity("aceta_app_api.Models.TamirciFirma", b =>
                {
                    b.Navigation("TamirciRandevular");
                });
#pragma warning restore 612, 618
        }
    }
}
